### ISSUE TITLE
Port Binding Errors

### ISSUE THREAD

**Issue by gespo89** [acme-dns/acme-dns#118]
Does this currently give any sort of visible error or warning if it can't bind the DNS port? I'll admit straight out that this largely is pebkac/rtfm error on my part, but I spent longer than I'd care to admit today troubleshooting today  because systemd-resolved was hogging the port on Ubuntu server, putting this in a state where everything looked green everywhere I checked, no more config errors, register and update work fine, but nothing will resolve for obvious(in retrospect) reasons. It would be nice to have something a bit more in your face, like when you have config errors and it straight up spits out an error and refuses to start.

**Comment by coling** [comment]
Seconded. I had the same issue. As systemd-resolved listens on 127.0.0.53:53 this blocks the all interfaces :53 default bind. Specifying 127.0.0.1:53 (for testing) or a real IP + port works fine. Some log information on this bind failure would be much appreciated (especially as systemd-resolved gets more widely deployed by default).

**Comment by coling** [comment]
Seconded. I had the same issue. As systemd-resolved listens on 127.0.0.53:53 this blocks the all interfaces :53 default bind. Specifying 127.0.0.1:53 (for testing) or a real IP + port works fine. Some log information on this bind failure would be much appreciated (especially as systemd-resolved gets more widely deployed by default).

**Comment by joohoi** [comment]
This should now be fixed!

**Comment by jvanasco** [comment]
duplicate of #70
