### ISSUE TITLE
Fix responses to be more standards compliant

### ISSUE THREAD

**Issue by lf-** [acme-dns/acme-dns#127]
http://dnsviz.net/d/auth.acme-dns.io/dnssec/

The authoritative bit should be set, which it isn't. 

NXDOMAIN responses appear to be incorrectly not returning SOA records. 

Requests for types which don't exist are incorrectly returning NXDOMAIN, while they should be returning NOERROR and no records instead. 

There's some more broken stuff too, including edns records, but this is a start.

**Comment by joohoi** [comment]
Thank you for opening the issue, you raise valid points. I'm going to look into this.

**Comment by joohoi** [comment]
I finally got around to implement the fixes. EDNS is now handled too (by indicating not implementing it). Sorry that it took so long, but should be fixed now.
