### ISSUE TITLE
Documentation and example config mismatch

### ISSUE THREAD

**Issue by jamestutton** [acme-dns/acme-dns#129]
Hi just testing this and firstly great project.  

One issue that caused me some issues though is the example docker config is mismatched with the example config.cfg  Issue being

docker -p53:53 binds tcp port 53 for the container whilethe example config.cfg is listening to udp port 53.

So it either needs -p 53:53/udp **preferred** or the config.cfg updated to protocol = "tcp"

```
docker run --rm --name acmedns                 \
 -p 53:53/udp                                      \
 -p 80:80                                      \
 -v /path/to/your/config:/etc/acme-dns:ro      \
 -v /path/to/your/data:/var/lib/acme-dns       \
 -d joohoi/acme-dns
```

As it stands I suspect a number of people new to docker will fall at this hurdle and this great project will not get the support or consideration it deserves.

**Comment by joohoi** [comment]
Thanks for your kind words, and nice catch! This should now be fixed in #130 . I decided to add a requested (and sane) feature to bind DNS listener to both - UDP and TCP ports at the same time. This combination should make `acme-dns` more convinient to use.
