### ISSUE TITLE
Question: readiness/liveness probe endpoints?

### ISSUE THREAD

**Issue by Kugelschieber** [acme-dns/acme-dns#136]
I'd like to run acme-dns in Kubernetes using Ingress. Is there a readiness/liveness HTTP endpoint? If there isn't one, can you add one (or let me create a PR for it)?

**Comment by joohoi** [comment]
There isn't one currently. If you would like to contibute, please go ahead! The current routes are added in [main.go](https://github.com/joohoi/acme-dns/blob/master/main.go#L127-L130) and implemented in [api.go](https://github.com/joohoi/acme-dns/blob/master/api.go).
