### ISSUE TITLE
How do I add the CNAME record to the server?

### ISSUE THREAD

**Issue by eknori** [acme-dns/acme-dns#14]
I can see in the video how to get the CNAME using dig, but how do I actually ADD the record? I think, this is missing in the video.

Sorry for asking such a dumb question. I am a developer :)

**Comment by eknori** [comment]
Ah, I think that I got it.

1. Register ONCE / keep credentials
2. MANUALLY add CNAME records to config.cfg
3. restart acme-dns
4. update TXT
5. on renewal goto 4

correct?

**Comment by joohoi** [comment]
Oh, no worries, there's no dumb questions, just bad documentation :)

Yes, everything else is correct, but the CNAME should be creaated manually to the actual nameserver the domain uses. So for example:

Your domain "example.com" you wish to get a certificate has nameservers hosted at provider X, and you run acme-dns on domain exampleauth.com.

After creating the acme-dns credentials using /register endpoint, you point CNAME record _acme-challenge.example.com using provider X nameservers to point to the randomly generated domain in exampleauth.com. This way you don't have to touch the X nameservers when renewing, and the automation updates the challenge token in acme-dns server that the originating domain points to using CNAME.

**Comment by joohoi** [comment]
Closing as resolved. Let me know if you still face problems and I'll reopen the issue.
