### ISSUE TITLE
default docker-compose is not synced with default config

### ISSUE THREAD

**Issue by kostyrev** [acme-dns/acme-dns#142]
I've noticed that docker-compose config [mounts](https://github.com/joohoi/acme-dns/blob/master/docker-compose.yml#L15) data directory into `/var/lib/acme-dns` but default config [does not uses](https://github.com/joohoi/acme-dns/blob/master/config.cfg#L30) it and that leads to data loss after container gets recreated.

**Comment by joohoi** [comment]
Oh, damn. You are completely right in this. Looks like a modification slipped in in commit f64de035 . This is completely a mistake from my side, I'll fix the default configuration file right away!

Thanks for opening issue!
