### ISSUE TITLE
DNS provider records for wildcard subdomains

### ISSUE THREAD

**Issue by Leosirth** [acme-dns/acme-dns#164]
Hi,

I'm trying to setup acme-dns with the purpose to use it to get wildcard SSL certificate using letsencrypt on traefik.

I'm a little confused on which record to add on the provider DNS and how to configure acme-dns.

Basically I want to issue a wildcard certificate for:

`*.example.com`

and my acme-dns host would be:

`acme-dns.example.com`

Is this possible? How should I configure the records on DNS provider and what to have in the "domain" and "nsname" of acme-dns config?

Looking at the readme I understand that if acme-dns host is:

`acme-dns.example.com`

than I can only have wildcard certificate as:

`*.acme-dns.example.com`

Is this correct?

Thanks for your help.
Best regards,

**Comment by mr-bolle** [comment]
@Leosirth how do you solve this topic? I don't have any suppored [provider](https://docs.traefik.io/configuration/acme/#provider) account, and i would use the wildcard certificates.
