### ISSUE TITLE
undefined: syscall.Umask when compiling under Windows with GoLang

### ISSUE THREAD

**Issue by SuperlativeIT** [acme-dns/acme-dns#165]
When I follow the instructions (https://github.com/joohoi/acme-dns#installation) for Windows deployment I get the following error:

go get github.com/joohoi/acme-dns/...
# github.com/joohoi/acme-dns
..\go\src\github.com\joohoi\acme-dns\main.go:22:2: undefined: syscall.Umask

Some research suggests that syscall.Umask does not exist in the Windows distro but I'm not sure how accurate that might be.

Please advise

Thank You

**Comment by SuperlativeIT** [comment]
Update:

I remarked out lines 12 and 22 in the main.go file and I am at least able to compile.

**Comment by SuperlativeIT** [comment]
I do seem to be a tad confused about one thing. in the config.cfg it notes:
domain = "auth.example.org"

Does this mean that I can only issue for subdomains for example.org or am I able to generate subdomains for any other domain such as abc123.com?

Thank You

**Comment by webprofusion-chrisc** [comment]
The domain in the config is the domain for the service, you can provide auth for any domain though.
