### ISSUE TITLE
Unable to query TXT records from _acme-challenge dns name

### ISSUE THREAD

**Issue by SuperlativeIT** [acme-dns/acme-dns#166]
I am able to resolve for the A record that is acmedns1.dnsserver.com.

I can query the cname record _acme-challenge.domain.com from google dns and the cname record points to subdomain.acmedns1.dnsserver.com.

I can query the txt record for subdomain.acmedns1.dnsserver.com when I point dig directly to the server and query it and it returns the stored txt value successfully.

However if I try to do the same through any other dns it fails to resolves and gives me an invalid domain error. 

At this point I'm spinning my wheels and getting nowhere. When I use auth.acme-dns.io everything validates successfully and I am issued a certificate. The only difference is my acme-dns vs yours. So I don't know what is making mine and yours act differently as I am using the supplied config.cfg with my domain values vs auth.example.org.

The root domain being used by acme-dns is registered with Google and hosted by Google DNS. The subdomain acmedns1.dnsserver.com is resolvable via dig and nslookup and points to the IP used by my acme-dns server.

At this point I can't seem to nail down the issue as everything appears to be correct.
So why am I not able to pull the TXT value when I query _acme-challenge.domain.com from my acme-dns server when I am able to do so when I use auth.acme-dns.io.?

What would cause a 3rd party DNS server not pick up the TXT record from acme-dns via port 53?

Thank you

Sincerely

**Comment by SuperlativeIT** [comment]
Using a domain name I personally owned I was able to get acme-dns up and running successfully on my home server and I was able to validate and receive a test certificate from LetsEncrypt. So I believe I now see the part that I'm missing from my work's deployment mainly due to their domain structuring but I'll find a way around it.

Thank you for your help

Sincerely

**Comment by butterl** [comment]
@SuperlativeIT 
I also meet this after renew the ssl cert  by hand， any solution to this issue？
I tried  change DNS to 8.8.8.8, but still failed
acme: Checking DNS record propagation using [8.8.8.8:53]
