### ISSUE TITLE
tls = "letsencrypt" and acme-dns.service

### ISSUE THREAD

**Issue by lateagain** [acme-dns/acme-dns#172]
Had a problem enabling ssl with tls = "letsencrypt" combined with the limited user service.

Followed the README to run as a service with user acme-dns and it only worked when run in the foreground. (could do with some logging for the certificate request).

Used lsof -p \<pid of acme-dns\> to see what the differences were. 
The cwd for the service is "\\" and it can't create the api-certs directory there.

Fixed by adding "WorkingDirectory=~" to the acme-dns.service file.

**Comment by joohoi** [comment]
Good to hear that you got it fixed. Another option to handle this would be to define a full path to `config.cfg` `acme_cache_dir`. This could be documented better in the installation instructions and / or the `config.cfg` itself.

**Comment by lateagain** [comment]
I added a pull request (set working directory in the systemd service file) because with the default  working directory the service can't create the "api-certs" directory for ssl certificate.

**Comment by joohoi** [comment]
Closing as resolved
