### ISSUE TITLE
Delete API endpoint

### ISSUE THREAD

**Issue by pauladams8** [acme-dns/acme-dns#177]
It would be nice to have an API endpoint to delete subdomain records that are no longer required.

Example:
`POST /delete`
```
{
    "subdomain": "8e5700ea-a4bf-41c7-8a77-e990661dcc6a"
}
```

**Comment by joohoi** [comment]
I personally prefer keeping the API as small as possible, and as the accounts take so very little storage space I see no urgent need for the endpoint. That said, I'm not strictly against this, and would probably accept a PR implementing the functionality.

**Comment by pauladams8** [comment]
I'd be happy to implement this, but it doesn't seem like there's much demand so I'll leave it for now.

**Comment by webcompas** [comment]
I think this would be very useful, especially if you have a lot of certificates which do the validation via acme-dns. I'll implement this and create a pull request.

**Comment by webprofusion-chrisc** [comment]
@webcompas  but why would you delete them? Do people create lots of subdomains that they don't need long term?

**Comment by webcompas** [comment]
Yes, at least in my case there are many testing systems which partially exist only for a short time. So we would like to keep the database clean from so many unused subdomains. As this isn't a big deal to implement I don't see a reason why this feature shouldn't be added.

**Comment by webcompas** [comment]
Please merge my pull request #209
