### ISSUE TITLE
Supports SQLite & PostgreSQL as DB backends

### ISSUE THREAD

**Issue by icelava** [acme-dns/acme-dns#178]
We learnt about ACME-DNS via the EFF article on options to make DNS challenges more automated and easier to handle.

https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation

This software has a feature statement "Supports SQLite & PostgreSQL as DB backends" but I am guessing the reality is one has to choose either SQLite or PostgreQL?

> INFO[0000] Using config file                             file=/etc/acme-dns/config.cfg
> ERRO[0000] Could not open database [unable to open database file]

I don't see any option to go with plain text zone files?

**Comment by joohoi** [comment]
Yeah, you need to choose one of those. Plain zone files support is not planned as for now.

**Comment by joohoi** [comment]
I'm closing this issue as resolved.
