### ISSUE TITLE
Where is "api-certs" supposed to land?

### ISSUE THREAD

**Issue by icelava** [acme-dns/acme-dns#184]
The first time I tested on my personal server/domain, I ran acme-dns directly as root user at /root/go/bin/acme-dns and the _api-certs_ directory appeared next to it shortly. I take it those will be stored at the executable's working directory?

On attempting to run acme-dns as a systemd service (with low-privilege acme-dns user) on our company's server/domain, we finally got the auto-certificate registration with Let's Encrypt. However I do not see any api-certs directory at the re-located /usr/local/bin/acme-dns executable directory, nor the home directory /var/lib/acme-dns (which hosts the database file).

Where is api-certs located in this context?

**Comment by lateagain** [comment]
Have a look at issue 172 < https://github.com/joohoi/acme-dns/issues/172 > I had the same question/problem

**Comment by icelava** [comment]
> Have a look at issue 172 < #172 > I had the same question/problem

Hmmm, but the thing is, acme-dns runs fine with the low-privilege acme-dns user account. It definitely registered its own cert with LE, since we can interface with it on HTTPS. Where would "api-certs" be for this case?

**Comment by icelava** [comment]
For whatever reason, this time round I managed to find the api-certs directory at /usr/local/bin/acme-dns the directory of the executable. So it is indeed relative the the process' _current working directory_. Strange why it did not show up with ls so many times last week.
