### ISSUE TITLE
tls = "letsencrypt" client still use ACMEv1?

### ISSUE THREAD

**Issue by NiasSt90** [acme-dns/acme-dns#186]
> time="2019-10-17T07:29:13Z" level=info msg="http: TLS handshake error from $IP: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details."

the time of ACMEv1 is over...

**Comment by joohoi** [comment]
~~Which version of `acme-dns` are you using at the moment?~~

edit: this is irrelevant

**Comment by joohoi** [comment]
Ok, so this is related to the Golang autocert package. The ACMEv2 was added as default just a few days ago.

I'll do a new release of `acme-dns` shortly.

**Comment by NiasSt90** [comment]
ok, thx. 
I've struggled into huge problems because of this, because it looks like the acme-dns REST api can't be access thru http-only. It always redirects to their own https endpoint (the documentation doesn't mentioned this) and therefore a ssl-cert is always needed to access the acme-dns rest api.

**Comment by joohoi** [comment]
On the upcoming weekend I'm planning to finish work towards migrating from `autocert` to [certmagic](https://github.com/mholt/certmagic), a few DNS RFC fixes and moving to automated challenge responses using DNS validation. This will fix a wide array of issues along with this one.

**Comment by joohoi** [comment]
> I've struggled into huge problems because of this, because it looks like the acme-dns REST api can't be access thru http-only. It always redirects to their own https endpoint (the documentation doesn't mentioned this) and therefore a ssl-cert is always needed to access the acme-dns rest api.

Acme-dns REST api can be accessed through HTTP, if you set `tls = "none"` in the `config.cfg`

**Comment by joohoi** [comment]
This was implemented in #190 and is included in v0.8 just released!
