### ISSUE TITLE
Source tarball incomplete?

### ISSUE THREAD

**Issue by danb35** [acme-dns/acme-dns#191]
The 0.8 source tarball is 46KB, and extracts into 220KB uncompressed.  By comparison, the 0.7.2 source tarball was 16MB, and a `git clone` of this repo is 27MB uncompressed.  Is there something missing from the 0.8 tarball, or does the `git clone` just include a lot of unnecessary stuff?

**Comment by joohoi** [comment]
There certainly is stuff missing, however - on purpose. Acme-dns was migrated over to Go 1.13 and gomodules in #187 and in the process I nuked the `vendor` directory where all the dependencies were saved. Closing this as resolved, but feel free to let me know you don't agree and we'll reopen the issue.

**Comment by danb35** [comment]
I just thought it was sure to be an error when it was that much smaller than it used to be, but so much the better.  I'm having trouble building a RPM from my old .spec file, but I'm green enough that it's probably a different error on my part.
