### ISSUE TITLE
Use example IP in documentation

### ISSUE THREAD

**Issue by AvverbioPronome** [acme-dns/acme-dns#219]
`192.0.2.53` or something from `192.0.2.0/24` instead of `198.51.100.1`

and something else in allowFrom. (`127.0.0.0/8` and `[::1]` included?)

"example and documentation" [reserved](https://en.wikipedia.org/wiki/Reserved_IP_addresses) ip classes are `192.0.2.0/24` and `2001:db8::/32`

**Comment by joohoi** [comment]
The same document you linked lists `198.51.100.0/24` for example and documentation as well, so I believe it's already correct.

**Comment by AvverbioPronome** [comment]
My bad, hadn't noticed. Sorry.
