### ISSUE TITLE
Maintained ? 

### ISSUE THREAD

**Issue by rgarrigue** [acme-dns/acme-dns#239]
Hi there

I wanted to know if this project is maintained before going for it ? At the time of writing latest commit is 6 months ago.

Best regards,

**Comment by Kugelschieber** [comment]
We have been using it for Emvi for more than a year and it's working as intended. It probably doesn't need that much maintenance as the Letsencrypt API doesn't change very frequently. So I'd say go for it. In case something doesn't work, joohoi is responding here and on Twitter and the project is simple enough to make changes yourself or ask the other users.

**Comment by Kugelschieber** [comment]
You might want to close this issue. joohoi just added a Go client for acme-dns and I can report that we are still running it successfully. Now for https://pirsch.io too.

**Comment by rgarrigue** [comment]
Indeed

NB, @Kugelschieber your https://pirsch.io/ is down

**Comment by Kugelschieber** [comment]
Thanks, I know :D Working on the network configuration, one of my favorite topics...
