### ISSUE TITLE
NS records with that host already exist. (Code: 81056)

### ISSUE THREAD

**Issue by sobujbd** [acme-dns/acme-dns#258]
I'm bit confuse about this description - [DNS Records](https://github.com/joohoi/acme-dns/blob/master/README.md#dns-records)

> You will need to add some DNS records on your domain's regular DNS server:

> NS record for auth.example.org pointing to auth.example.org (this means, that auth.example.org is responsible for any *.auth.example.org records)
A record for auth.example.org pointing to 198.51.100.1

On **Cloudflare** 
I do able to add this,
Type | Name | Content
------ | ------- | ---------
NS | acme-dns | acme-dns.example.org

But, When I'm trying to add this,
A | acme-dns | 89.89.89.89
---- | ------- | --------------

I had received **NS records with that host already exist. (Code: 81056)**

And If I add the DNS record such as way,

Type | Name | Content
------ | ------- | ---------
NS | acme-dns | ns.acme-dns.example.org
A | ns.acme-dns | 89.89.89.89

And set the **config.cfg** file
```
# domain name to serve the requests off of
domain = "acme-dns.example.org"
# zone name server
nsname = "ns.acme-dns.example.org"
# admin email address, where @ is substituted with .
nsadmin = "admin.ns.acme-dns.example.org"
# predefined records served in addition to the TXT
records = [
    # domain pointing to the public IP of your acme-dns server 
    "acme-dns.example.org. A 89.89.89.89",
    "ns.acme-dns.example.org. A 89.89.89.89",
    # specify that auth.example.org will resolve any *.auth.example.org records
    "acme-dns.example.org. NS ns.acme-dns.example.org.",
]
```
The host **acme-dns.example.org** could not resolve!

How do you setup this - https://toolbox.googleapps.com/apps/dig/#NS/@ns.auth.acme-dns.io.

**Comment by AvrumFeldman** [comment]
From a quick google it seems that Cloudflare doesn't support glue records. Your alternative should be working. Can you confirm that your acme-dns server is responding to queries when directly queried?

**Comment by sobujbd** [comment]
@AvrumFeldman,
> From a quick google it seems that Cloudflare doesn't support glue records. Your alternative should be working. Can you confirm that your acme-dns server is responding to queries when directly queried?

It's something wrong with Cloudflare. As you said, maybe it's that the Cloudflare doesn't support **glue** records. 

This [DNS setup instruction](https://github.com/joohoi/acme-dns/blob/master/README.md#dns-records) works with **Namecheap** DNS Hosting.

**Comment by rodrigodc** [comment]
It works with **Cloudflare** if you:

- Set `A ns-acme-dns` pointing to your public IP address in Cloudflare, **and**
- Set `NS acme-dns` pointing to `ns-acme-dns` in Cloudflare, **and**,
- Start with the _default_ acme-dns `config.cfg`, **and**
- Adjust it for your domain name (_without_ the `ns-` prefix) and public IP address.

The first and second itens work around Cloudflare's limitation `NS records with that host already exist. (Code: 81056)`.

**Comment by gruentee** [comment]
Nice, thanks for the hint. I'll try that .
