### ISSUE TITLE
acme-dns returning a 401- error:forbidden message

### ISSUE THREAD

**Issue by DutchForeigner** [acme-dns/acme-dns#259]
Hi, I'm having a problem with updating the TXT record(s). 
Hopefully someone can shed some light on this issue.
It used to be working ok when I initially set it up almost 3 months ago, and of course when the cert is about to expire, it now fails....

When I'm using  **sudo certbot renew --dry-run**,  it fails with an error:

`</etc/letsencrypt/acme-dns-auth.py" returned error code 1`>

`<Encountered an error while trying to update TXT record in acme-dns.`>
`<------- Request headers:`>
`<{`>
`<  "Content-Type": "application/json",`>
`<  "X-Api-Key": "$2a$10$Ndg6bTFaIbgM7PazM8fdkO3uM77HC4VtHoIE1aI7fdi1.hRnigMd.",`>
`>  "X-Api-User": "b2651f52-e31d-438e-8230-1bceefd51756"`>
`<}`>
`<------- Request body:`>
`<{`>
`<  "subdomain": "59932ad1-6332-4057-bee9-7c96ed003a64",`>
`<  "txt": "bpUcVQE5Jl51EqME87gLatSZSwiZpe0dTZh9TxJVBXM"`>
`<}`>
`<------- Response HTTP status: 401`>
`<------- Response body: {`>
`<  "error": "forbidden"`>
`<}`>

Also when trying to do the update using curl, it fails with the same error: 401 - forbidden.

`<curl --location --request POST 'https://auth-acme-dns.nexusnet.me:10443/update' \
--header 'X-Api-User: b2651f52-e31d-438e-8230-1bceefd51756' \
--header 'X-Api-Key: $2a$10$Ndg6bTFaIbgM7PazM8fdkO3uM77HC4VtHoIE1aI7fdi1.hRnigMd.' \
--header 'Content-Type: application/json' \
--data-raw '{
    "subdomain": "59932ad1-6332-4057-bee9-7c96ed003a64",
    "txt": "___validation_token_received_from_the_ca___"
}'`>

- I've the acme-dns client installed locally on a raspberry pi, on port 10443
- The health check comes back with code 200:
     - `<curl --location --request GET 'https://auth-acme-dns.nexusnet.me:10443/health'`>
- the created user for use with the service deamon, 'acme-dns', does have rights to the sqlite3 db, (I can update a record using sqlite3 from the command line)

**Comment by deathsonic18** [comment]
I too am having this issue, with cert-manager

**Comment by joohoi** [comment]
This must be due some kind of change from cert-manager end. More precisely due to how it handles the credentials. The `X-Api-Key` that has been passed looks like a bcrypt hash instead of the proper API key provided by `acme-dns`

**Comment by DutchForeigner** [comment]
In my case, it was something wrong in the database (which I likely screwed up myself)
I 'fixed' it by:

1. stop acme-dns (**sudo systemctl stop acme-dns**).
2. delete the database file (**rm /var/lib/acme-dns/acme-dns.db**).
3. start acme-dns client service again (**sudo systemctl stop acme-dns**).
4. Do a new registration (**https://auth-acme-dns.nexusnet.me:10443/register**) Note: I have the port changed to 10443 as I've an automation webserver on the same box.
5. Use the new registered details in the update command. -> this now worked for me.

Just as FYI: 
While testing, I found it useful to stop the acme-dns service and run the acme-dns client directly (**sudo /usr/local/bin/acme-dns/acme-dns**). That way it is showing details on the command line while you're executing acme-dns client related commands via another box (like registering, updating, DNS query etc).
You can check the records in the database directly if need be by installing/using sqlite3:
**sudo sqlite3 /var/lib/acme-dns/acme-dns.db**
sqlite> **.mode line**
sqlite> **select * from records;**  -> this will give you the registered account details.
sqlite> **select * from txt;**  -> this will give you the TXT records.
**.exit** or **Ctrl-D** to exit

**Comment by deathsonic18** [comment]
For me, I am trying to host it on GCP. I used the READ.ME on github and then turned to this 
https://medium.com/emvi/wildcard-ssl-certificates-on-kubernetes-using-acme-dns-fde583a69eb5. 
With version 0.7.2 i get a ssl wrong version and with 0.8 i just get a connection refused. 
When I check the the acme-dns.db tables in my /data folder, it doesnt seem to be storing any information in the .tables

**Comment by leggewie** [comment]
@DutchForeigner If your problem is solved, can you kindly close the ticket?
