### ISSUE TITLE
Solving ACME challenge without exposing subdomain names in DNS

### ISSUE THREAD

**Issue by shalak** [acme-dns/acme-dns#281]
When I want to obtain LE certificate for foo.example.com, I need to add a `_acme-challange.foo.example.com` CNAME to my DNS. But this exposes the information that I'm running a server named `foo` in my infrastructure.

Is there a way for me to obtain multiple LE certificates, each for different subdomain, but only add the `_acme-challange.example.com`? 

When I tried to do this, the `acme-dns-client`-driven certbot returns error:
```
Hook '--manual-auth-hook' for foo.example.com reported error code 1
Hook '--manual-auth-hook' for foo.example.com ran with output:
 [!] Domain foo.example.com does not have acme-dns account registered for it. Validation failed.
 acme-dns-client - v0.2
```

**Comment by Zetanova** [comment]
Your problem has nothing to do with acme-dns.

You need to generate a wildcard cert `*.example.com` and use it for `foo.example.com` service.

**Comment by joohoi** [comment]
There should not be any issues for having multiple wildcard certificates generated using acme-dns. Wildcard certificates are your only option for hiding the subdomain names though, as all names registered for certificates get published in Certificate Transparency logs.

**Comment by shalak** [comment]
Thank you for the answers, I'll close the ticket.
