### ISSUE TITLE
NS fallback for queries unrelated to Letsencrypt

### ISSUE THREAD

**Issue by mathroc** [acme-dns/acme-dns#284]
If I understand correctly, all A DNS queries return the same IP, would it be possible to configure acme-dns to fall back to another DNS server for query unrelated to Letsencrypt instead of always answering with the same IP?

I'd like to use that with https://github.com/cunnie/sslip.io/ for local development. I think this would let Traefik (or any Letsencrypt client able to talk with acme-dns) to generate certificate automatically for even for hostname resolving to local addresses

**Comment by joohoi** [comment]
Thanks for sending in the question; It kind of could, but as acme-dns is not designed to serve as an actual DNS server outside of doing ACME DNS validation, I'd hate to encourage people to configure it to do something else. This would also unnecessarily complicate the current codebase.

Closing this issue now, but feel free to comment if something was left unclear and we'll open if a need arises.
