### ISSUE TITLE
No cert generated

### ISSUE THREAD

**Issue by blackbasket** [acme-dns/acme-dns#297]
Hi guys,

I did a fresh install of acme-dns.

I am unable to connect using https. If I change the config to 80/none, the curl request is good.

With 443/letsencrypt(staging) I always receive `error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error`.

Shouldn't the required cert being generated automatically? Or what do I have to do?

I cannot find anything concerning this, what helps.

Regards,
Marcel

**Comment by saschaludwig** [comment]
Hi, I have the same problem with a33c09a, the cert is never be created.
Below is my config, configured ports are open and and reachable.

Every time I restart the service, I get this message in the log, but it never ever tries to get a certificate. At least I can't see anything bout it in the log.
`
Apr 01 02:38:44 flux acme-dns[232945]: time="2022-04-01T02:38:44+02:00" level=info msg="2022/04/01 02:38:44 [INFO][FileStorage:api-certs] Lock for 'issue_cert_flux.rc5.de' is stale (created: 2022-04-01 00:10:01.08155592 +0200 CEST, last update: 2022-04-01 02:38:34.943066241 +0200 CEST); removing then retrying: api-certs/locks/issue_cert_flux.rc5.de.lock"
`

Config:
```
[general]
listen = ":53"
protocol = "udp"
domain = "flux.rc5.de"
nsname = "flux.rc5.de"
nsadmin = "some.email.de"
records = [
    "flux.rc5.de. A 136.243.142.31",
    "home.astrastudio.de. A 136.243.142.31",
    "home.astrastudio.de. NS flux.rc5.de.",
]
debug = true

[database]
engine = "sqlite3"
connection = "/var/lib/acme-dns/acme-dns.db"

[api]
ip = "0.0.0.0"
disable_registration = false
port = "9988"
tls = "letsencrypt"
acme_cache_dir = "api-certs"
notification_email = "some@email.de"
corsorigins = [
    "*"
]
use_header = false
header_name = "X-Forwarded-For"

[logconfig]
loglevel = "debug"
logtype = "stdout"
logformat = "text"
```

What can I do to hunt this bug? Where do I get more info/more debug output?

**Comment by saschaludwig** [comment]
I had the same problems.
My DNS/NS entries in my main zone were wrong, and additionally I ran into a rate limit on the letsencrypt server.

**Comment by gbonnefille** [comment]
While configuring the tools, it is highly recommended to use the [staging environment](https://letsencrypt.org/docs/staging-environment/).

**Comment by saschaludwig** [comment]
> While configuring the tools, it is highly recommended to use the [staging environment](https://letsencrypt.org/docs/staging-environment/).

I did this and received a valid staging cert, but one of my DNS servers was out of sync and had other/old records. Looks like I got luck with the staging environment, just asked the correct nameserver and the production server did ask the outdated one. ;-)

**Comment by gbonnefille** [comment]
> > While configuring the tools, it is highly recommended to use the [staging environment](https://letsencrypt.org/docs/staging-environment/).
> 
> I did this and received a valid staging cert, but one of my DNS servers was out of sync and had other/old records. Looks like I got luck with the staging environment, just asked the correct nameserver and the production server did ask the outdated one. ;-)

How fast did you get banned from Let's Encrypt?
I remember my first attempts with cert-manager, whithout knowing staging environment, and I was banned in... few seconds :D

**Comment by blackbasket** [comment]
Ok, I have gotten a cert now... I had to change the listing IP from localhost... 



```
[general]
# DNS interface. Note that systemd-resolved may reserve port 53 on 127.0.0.53
# In this case acme-dns will error out and you will need to define the listening interface
# for example: listen = "127.0.0.1:53"
listen = "172.31.50.40:53"
# protocol, "both", "both4", "both6", "udp", "udp4", "udp6" or "tcp", "tcp4", "tcp6"
protocol = "both4"
```

But I still do not get any logs... I want to log into a file, but do not receive any logs in the console as well (with stdout logtype of course)...
```
# debug messages from CORS etc
debug = true

[logconfig]
# logging level: "error", "warning", "info" or "debug"
loglevel = "debug"
# possible values: stdout, TODO file & integrations
logtype = "TODO"
# file path for logfile TODO
logfile = "/tmp/acme-dns.log"
# format, either "json" or "text"
logformat = "text"
```

**Comment by saschaludwig** [comment]
> want to log into a file

That is not possible right now, as the config says:
`# possible values: stdout, TODO file & integrations`
so the only option is stdout

Depending on the OS you use, you can get logfiles via systemd or just run acmedns on the commandline in foreground:
`$ journalctl -u acme-dns -f`

**Comment by blackbasket** [comment]
Thanks, @saschaludwig ... I got this wrong... I like Win & Mac ;) I will try with `journalctl`...

**Comment by blackbasket** [comment]
Thank you @saschaludwig ... it was a DNS config issue, I overlook many times...
