### ISSUE TITLE
Will systemd-resolve get in the way?

### ISSUE THREAD

**Issue by thedarb** [acme-dns/acme-dns#304]
My standard Ubuntu systems (20.04 - 22.04) all came configured with systemd-resolve parked on the DNS port (53):
```
$ sudo netstat -lpn | grep ":53 "
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      710/systemd-resolve 
udp        0      0 127.0.0.53:53           0.0.0.0:*                           710/systemd-resolve 
```
I'm thinking if I want to run this as a Docker container, I might need to set it up with it's own IP on my lan for this.  I suppose I could disable systemd-resolv, but I don't yet know the implications of trying that.  Thoughts?

**Comment by thedarb** [comment]
Nevermind. :)

**Comment by Ajedi32** [comment]
In the interest of avoiding "nevermind, I fixed it" syndrome here:

Yes, it does interfere, and the solution is either to update the `listen` option in `config.cfg` to bind to a specific IP address (such as 127.0.0.1, or the public IP of your box), or set `DNSStubListener=no` in `/etc/systemd/resolved.conf` to stop systemd from listening on that port. (And [manually update the `resolv.conf` symlink if you're running systemd <v246](https://github.com/systemd/systemd/issues/14700#issuecomment-1046279509).)

**Comment by thedarb** [comment]
Yep, binding it to 127.0.0.1 did it for me.  Ubuntu 22.04.  Thank you.
