### ISSUE TITLE
Support of DuckDNS.org API

### ISSUE THREAD

**Issue by stokito** [acme-dns/acme-dns#323]
Hi @joohoi thank you for your project. I came with a similar idea.
But I need more simple API that will use only GET request. Yes, it's not nice but there is a reason for this.
Please read the thread
https://community.letsencrypt.org/t/dns-api-standard-or-specification/189887/6

**Comment by joohoi** [comment]
Hi, thanks for opening the issue. 

I'm having a bit hard time understanding the scenario here. Using acme-dns for DNS validation should not require the user to do anything else on their DNS zone than to create a single permanent CNAME record and the acme-dns server itself doesn't do any API integrations itself.
