### ISSUE TITLE
systemd socket activation

### ISSUE THREAD

**Issue by logic** [acme-dns/acme-dns#34]
systemd provides socket activation as an option for listening services, and is particularly handy for services that listen on privileged ports. It would be useful to be able to operate a very infrequently-accessed service like this via on-demand activation.

It looks like [miekg/dns](https://github.com/miekg/dns) already supports socket activation via `ActivateAndServe` (analogous to `ListenAndServe`), and [coreos/go-systemd](https://github.com/coreos/go-systemd) provides a handy activation abstraction.

(And because you can configure multiple listeners, it would be easy to also grab the listener for HTTP from systemd as well.)

**Comment by joohoi** [comment]
This looks interesting, however I'd be a bit careful to implement (at least as a default) things that are very dependent on the users systemd configuration. It's different, of course, when and if this would be packaged for certain distributions, allowing automatic setup of such systemd features.

This is the first time I read of such feature. Could you elaborate the impact and usefulness? I think I'm missing something, but if the service(s) would be activated upon incoming connection, all I can see is a slight overhead in the initial connection. Acme-dns doesn't reserve too much of resources currently, so I don't see an immediate need for this. But as said, I'm new to the feature so please correct me as I obviously have something wrong here.
