### ISSUE TITLE
registration with invalid `allowfrom` fails open

### ISSUE THREAD

**Issue by cpu** [acme-dns/acme-dns#43]
I didn't read the documentation very carefully and thought I could POST `/registration` with an `allowfrom` entry for a single host address instead of a CIDR range, e.g.:

```
{
    "allowfrom": [
        "127.0.0.1"
    ]
}
```

`acme-dns` filters this invalid `allowfrom` in `acmedb.Register` using `cidrslice.ValidEntries`.  The registration is created successfully with no errors, but the returned `allowfrom` is empty and so is the field in the database for this user:
```
{
  "username": "<rand>",
  "password": "<rand>",
  "fulldomain": "<rand>.example.com",
  "subdomain": "<rand>",
  "allowfrom": []
}
```

The documentation specifically says to use a CIDR range but I think there might be a case to be made for rejecting the registration with an error when the `allowfrom` contains invalid entries. Since `allowfrom` is a security control I think `acme-dns` should be conservative and fail fast when it can't fulfill the request as received.

@joohoi What do you think?

**Comment by joohoi** [comment]
I think you are on the right track here, and we should fail early. But from the UX perspective, I think what would be best way to handle this, would be to automatically add `/32` bitmask if none is specified but the IP address itself is valid.

**Comment by cpu** [comment]
>  from the UX perspective, I think what would be best way to handle this, would be to automatically add /32 bitmask if none is specified but the IP address itself is valid.

That sounds like a nice compromise :+1:

**Comment by joohoi** [comment]
This is now finally fixed. I opted to not to introduce magic I proposed in https://github.com/joohoi/acme-dns/issues/43#issuecomment-369604662 . The only magic is removing `[` and `]` from the IP addresses as the `net.ParseCIDR` cannot handle that notation of IPv6 addresses.
