### ISSUE TITLE
using it with different clients

### ISSUE THREAD

**Issue by marrco** [acme-dns/acme-dns#56]
is there a script available to use it with acme.sh
https://github.com/Neilpang/acme.sh
https://github.com/Neilpang/acme.sh/tree/master/dnsapi

or with  getssl ?
https://github.com/srvrco/getssl

tia #

**Comment by joohoi** [comment]
I don't think there is one yet. I created an example auth hook for Certbot, that can be found here: [https://github.com/joohoi/acme-dns-certbot](https://github.com/joohoi/acme-dns-certbot) . It is written in Python however, so I'm not sure if that would be directly usable in acme.sh or getssl. 

My shell scripting-fu isn't strong enough to play around with decent ways to store the credentials and fetching them on the later runs unfortunately.

I'll create a new issue tracking the client implementations.

**Comment by joohoi** [comment]
I opened a tracking issue and a general call for help for this: #59
