### ISSUE TITLE
How do I make the subdomain.auth.domain.tld available from the outside

### ISSUE THREAD

**Issue by jazzdd86** [acme-dns/acme-dns#57]
Hi I created a docker container for acme-dns, I registered there and I can update the token via post request. I am using the jwilder nginx proxy.
I installed a CNAME entry for _acme-challenge.jotunheim.de to subdomain.auth.jotunheim.de
This entry points to my IP adress.
What I don't understand is, what I need to do now, to make the TXT entry available from the outside. Do I need to portforward port 53 to the inside acme-dns, right? What else?

**Comment by joohoi** [comment]
>  What  I don't understand is, what I need to do now, to make the TXT entry  available from the outside. Do I need to portforward port 53 to the  inside acme-dns, right? What else?

Yeah, you will need to expose the DNS port on the host. In addition to that you will need the following . I'm making the assumption that you are running acme-dns in `auth.jotunheim.de` and that the public IP address of the acme-dns instance is `10.10.10.10` (obiviously false):

Main DNS zone for `jotunheim.de`:

- NS record telling a requesting client to ask domains under `auth.jotunheim.de` from the acme-dns instance. For example: `auth.jotunheim.de. NS ns.auth.jotunheim.de`
- A / AAAA record for the server that you targeted the NS record to. for example: `ns.auth.jotunheim.de  A  10.10.10.10`, where the IP is naturally the address of your acme-dns instance.

Acme-dns static records configuration in `config.cfg`:

```
records = [
    # default A
    "auth.jotunheim.de. A 10.10.10.10",
    # A 
    "ns.auth.jotunheim.de. A 10.10.10.10",
    # NS
    "auth.jotunheim.de NS ns.auth.jotunheim.de.",
]
```

**Comment by jvanasco** [comment]
It would make sense to extend the instructions to add the following:

1. How to set up DNS CNAMEs for all domains you want to handle
2. How to set up DNS (A record, NS records) for your instance of acme-dns

**Comment by joohoi** [comment]
This is in the works! In PR #64
