### ISSUE TITLE
raise an error if acme-dns can't listen/bind to a specified port.

### ISSUE THREAD

**Issue by jvanasco** [acme-dns/acme-dns#70]
while doing some debugging of firewall rules, I realized that acme-dns will start up fine as an unprivileged user who can't bind to port 53 (if that is the configured port).  I think it should probably raise an error OR print a warning line in these situations.

**Comment by mearsten** [comment]
#85 fixes that

**Comment by Ajedi32** [comment]
Pretty sure this is a duplicate of #118, and is now fixed in #122

**Comment by jvanasco** [comment]
well, #118 is a duplicate of this - and it looks like printing a warning is handled by #122.

@joohoi does #122  only log a warning, or can it cause a fatal error if unable to bind?

**Comment by joohoi** [comment]
> does #122 only log a warning, or can it cause a fatal error if unable to bind?

Both, it calls `log.Fatal(err)` which logs the error, and then exits. :)
