### ISSUE TITLE
TCP or UDP? Why not both?

### ISSUE THREAD

**Issue by Ajedi32** [acme-dns/acme-dns#80]
acme-dns has a config option that lets you choose whether to serve DNS requests over UDP or over TCP.

However, [RFC7766 requires that](https://tools.ietf.org/html/rfc7766#section-5):

> All general-purpose DNS implementations MUST support both UDP and TCP transport.

And unfortunately, "both" doesn't seem to be an option.

**Comment by joohoi** [comment]
Thanks for opening the issue, you are right and this should get fixed.

**Comment by joohoi** [comment]
Aaaand it's finally fixed.
