### ISSUE TITLE
SQLite database is world-readable by default

### ISSUE THREAD

**Issue by Ajedi32** [acme-dns/acme-dns#82]
The acme-dns database contains sensitive information such as API keys, and should not be readable by other Linux users by default. However, when I run acme-dns it creates the `acme-dns.db` file with its permission bits set to 644.

**Comment by joohoi** [comment]
This definitely is a bug, and should be fixed! Thanks for opening the issue!

**Comment by Ajedi32** [comment]
Worth noting this issue is somewhat mitigated by the fact that the API keys are randomly generated, 40 characters long, and hashed with Bcrypt, so a database leak is very unlikely to result in usable credentials for an attacker.
