### ISSUE TITLE
Problem start acme-dns in installation

### ISSUE THREAD

**Issue by LinuxCuba** [acme-dns/acme-dns#98]
After install and config. exec acme-dns 
this error not start the service.
INFO[0000] Using config file                             file=/etc/acme-dns/config.cfg
ERRO[0000] Could not open database [sql: unknown driver "" (forgotten import?)]

**Comment by joohoi** [comment]
I’m sorry that tou are experiencing issues with acme-dns. We just had a
similar issue, I wonder if this is the case with your configuration as
well:
https://github.com/joohoi/acme-dns/issues/93#issuecomment-402906927

**Comment by LinuxCuba** [comment]
Yes, but driver is sqlite3 in debian system.

**Comment by joohoi** [comment]
Yeah, in the referenced issue, the actual problem was missing quotes around
the configuration value. I believe this is rather config parser than db
driver issue.

**Comment by LinuxCuba** [comment]
How to solve and fix this problem please, i need start the server.

**Comment by joohoi** [comment]
Please see
https://github.com/joohoi/acme-dns/issues/93#issuecomment-402092630

And
https://github.com/joohoi/acme-dns/issues/93#issuecomment-402487006

**Comment by joohoi** [comment]
Are you sure that the file `/etc/acme-dns/config.cfg` can be read by the user that acme-dns is started with? There is an outstanding PR that makes the error messages more elaborate, but the error you are seeing can also indicate the acme-dns wasn't able to read the configuration file.

**Comment by joohoi** [comment]
The current `master` as well as the new release v0.5 have vastly improved error messages. You could retry with either of those to figure out what's the underlying issue.

**Comment by LinuxCuba** [comment]
Yes i sure the file config is read by user acme-dns;
`root@certbot:/# ls -l /etc/acme-dns
total 6
-rw-r--r-- 1 acme-dns acme-dns 2167 Aug  9 17:37 config.cfg
`
`root@certbot:/# ls -ld /etc/acme-dns
drwxr-xr-x 2 acme-dns acme-dns 3 Aug 13 11:47 /etc/acme-dns`

**Comment by joohoi** [comment]
If you are not able to figure out the underlying issue by trying to run the latest version (the Docker Hub container image is also updated), could you please pastebin the contents of your `config.cfg`. GitHub formatting often breaks because of the config syntax.

**Comment by LinuxCuba** [comment]
How to update, replaced all fille??

**Comment by joohoi** [comment]
I would delete the files you have installed now, and start the installation from the beginning.

**Comment by LinuxCuba** [comment]
ohh bad.

**Comment by LinuxCuba** [comment]
Update acme-dns this the new error in release v0.5
`root@certbot:/# acme-dns
INFO[0000] Using config file                             file=/etc/acme-dns/config.cfg
ERRO[0000] Encountered an error while trying to read configuration file:  Near line 45 (last key parsed 'api'): expected a top-level item to end with a newline, comment, or EOF, but got 't' instead`

**Comment by joohoi** [comment]
Yeah, there seems to be a syntax error in your configuration file. Please double verify.

**Comment by LinuxCuba** [comment]
corrected in api the value of the tls change let`s encrypt by cert, but now I get a new unknown error.

`INFO[0000] Using config file                             file=/etc/acme-dns/config.cfg
ERRO[0000] Encountered an error while trying to read configuration file:  toml: cannot load TOML value of type string into a Go boolean`

**Comment by joohoi** [comment]
Check the default `config.cfg` against your edited configuration, and look for quote marks ( `"` ). Boolean values should not be quoted.

**Comment by LinuxCuba** [comment]
Yes already worked, it had a double quote in a Boolean value.
but this error when trying read the datebase.
`ERRO[0000] Could not open database [file is not a database]`
How to create the database and what is your structure?

**Comment by LinuxCuba** [comment]
Remove the file /var/lib/acme-dns/acme-dns.db, and start again, and work perfect. Thank.

**Comment by joohoi** [comment]
> it works in the terminal with the acme-dns command executing directly, but it does not start the service with systemd

I don't have a direct answer to that one, as I don't know what the problem might be. Some things you could check:
- If the systemd service specifies a unprivileged user for running acme-dns, check that the configuration path is readable by that user, and the database is writable by the said user.
- acme-dns exists on a correct path
- If acme-dns is configured to serve on default (privileged) ports, make sure it has the privileges to do so.
